<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FSH.Modules.Academics.Contracts</RootNamespace>
		<AssemblyName>FSH.Modules.Academics.Contracts</AssemblyName>
		<PackageId>FullStackHero.Modules.Academics.Contracts</PackageId>
		<NoWarn>$(NoWarn);S2094</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Mediator.Abstractions" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
	</ItemGroup>

</Project>
